# Generated by Django 5.2.4 on 2025-07-31 03:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_picture_upload_path, validators=[users.models.validate_image_file_extension, users.models.validate_file_size]),
        ),
    ]
