# Generated by Django 5.2.4 on 2025-08-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
