# Generated by Django 5.2.4 on 2025-08-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='playlists',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='playlists.movie'),
        ),
    ]
